apiVersion: apps/v1
kind: Deployment
metadata:
  name: oessoncapstone
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oessoncapstone
  template:
    metadata:
      labels:
        app: oessoncapstone
    spec:
      containers:
      - name: oessoncapstone
        image: florinelfrancisc/oessoncapstone:1.0
        ports:
        - containerPort: 8080
        env:
        - name: GREETING
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GREETING
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: API_KEY
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
        securityContext:
          runAsUser: 1001
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
