apiVersion: v1
kind: Service
metadata:
  name: oessoncapstone-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: oessoncapstone
  ports:
    - name: http           
      protocol: TCP
      port: 80
      targetPort: 8080
