apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oessoncapstone-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring-prometheus
spec:
  selector:
    matchLabels:
      app: oessoncapstone
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
